### ISSUE TITLE
Using ggiraphExtra in Shiny context? 

### ISSUE THREAD

**Issue by ThoDuyNguyen** [cardiomoon/ggiraphExtra#1]
Could we use this package in Shiny context? 

Thank you in advance.

**Comment by cardiomoon** [comment]
Of course! You can use in Shiny app.
Please use ggiraphOutput instead of plotOutput in ui.R. 
Please use renderggiraph in server.R

**Comment by ThoDuyNguyen** [comment]
Thank you.
