### ISSUE TITLE
use girafe instead of ggiraph

### ISSUE THREAD

**Issue by davidgohel** [cardiomoon/ggiraphExtra#10]
Dear Keon-Woong Moon

Since September 2019 we decided to refactor ggiraph API. Now it comes with many more options and  almost 100% of ggplot2 geoms are implemented... We also add interactive themes, scales and legend.

To enable that, we had to clean the code and the API, as a result, function `girafe` should be used instead of `ggiraph` (that does not provide all these features). 

https://davidgohel.github.io/ggiraph/reference/ggiraph.html

> This function is maintained for backward compatibility reasons, user shoud now use function girafe and girafe_options.

As we will prepare a submission soon, would you be ok to use `girafe` in your code? That way we can deprecate the function (and stop confusing users ;) ).

KR
David

**Comment by cardiomoon** [comment]
Dear David,

Thank you for asking.
When are you going to  submit the updated ggiraph? I will prepare the update of my package.

Best,

Keon-Woong Moon

**Comment by davidgohel** [comment]
I think I will push the new release soon but I will wait for you before deprecation of `ggiraph` :)
If you don't have time for this at the moment, we won't deprecate `ggiraph` for the new submission and will wait for the next release.

Best,
David

**Comment by cardiomoon** [comment]
Thank you very much !
Frankly speaking, I am a cardiologist working at university hospital, South Korea . 
Right now, I am too busy to recode my packages due to corona pandemic.
Please do not deprecate ggiraph this time. I will rewrite my package soon.    
Best,
Keon-Wong Moon

**Comment by davidgohel** [comment]
Sure, no problem. Don't waste your time with that. I fully understand and will create a PR later (not before a month at least). We will not deprecate ggiraph now.

**Comment by cardiomoon** [comment]
Thank you for your understanding.
And I really appreciate you and your packages.
Keon-Woong Moon
