### ISSUE TITLE
ggpredict3d

### ISSUE THREAD

**Issue by Saadi4469** [cardiomoon/ggiraphExtra#16]
Hello,

Has the ggPredict3d() function been removed from the current version of the package on CRAN?

Cheers,

**Comment by cardiomoon** [comment]
Dear Saadi4469,
Please use predict3d  package on CRAN or github.
There are functions ggPredict() and predict3d().
I don't know about ggPredict3d().

Best,

**Comment by Saadi4469** [comment]
Thank you for your suggestion.

Cheers,
