### ISSUE TITLE
ggPredict gives the "could not find function "."" error if plyr is not a loaded library

### ISSUE THREAD

**Issue by timraiswell** [cardiomoon/ggiraphExtra#2]
I kept receiving that error until I loaded Plyr over the top of tidyverse / tidyquant. ggPredict works fine with the plyr package loaded.

**Comment by cardiomoon** [comment]
Please use predict3d::ggPredict(). 
Thank you.

**Comment by Mathecon** [comment]
I am relatively new to R and I came across the ggPredict function and tried it and got the following error message:
"Error in ggPredict(Ohlsonlogit, se = TRUE, interactive = TRUE, digits = 3) : 
  could not find function "ggPredict""
where "Ohlsonlogit" is the name of the object (file) from a glm fit for a logit model. I searched far and wide on the internet and tried every piece of advice--including the one here--and I am unable to get ggPredict installed uder anyone of the myriad packages that it supposedly resides in. Alas, I will resort to my ggplot()+geom_Line(), etc to generate the plots. If any reader of this comment knows of a recent successful installation of ggPredict please post a comment to that effect. Thanks in advance
