### ISSUE TITLE
error with factors

### ISSUE THREAD

**Issue by maxgav13** [cardiomoon/ggiraphExtra#5]
I was trying the ggPredict() function and the examples were working fine but as soon as I tried with my own example models involving factor variables I got this error:
_Error in Summary.factor(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  : 
  ‘min’ not meaningful for factors_
I don´t understand why an example model with factor variable (fit1=lm(NTAV ~ age+sex,data=radial)) works and when I try to use my own (mod = lm(Temp ~ Wind*Month,airquality)) it doesn´t
Thanks

**Comment by jenniferdodd** [comment]
Hi, 
I have had the same issue, did you find a solution? 
Thanks

**Comment by ttanvitaparia** [comment]
Hi,
I ran into the same problem now. 
Is there a development?

**Comment by cardiomoon** [comment]
Please use my new package predict3d::ggPredict().
I have released package predict3d on CRAN yesterday.
